# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Builder Stage: Install deps and build with bun
FROM node:18-alpine AS builder

# Install curl and bash for bun install script
RUN apk add --no-cache curl bash

# Install bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:${PATH}"

WORKDIR /app

# Copy lockfiles and package manifests
COPY package.json bun.lock package-lock.json ./

# Install dependencies with bun
RUN bun install --ignore-scripts

# Copy source code
COPY . .

# Build TypeScript to JavaScript
RUN bun run build

# Runner Stage: minimal image to run the CLI
FROM node:18-alpine

WORKDIR /app

# Copy built binaries and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Default entrypoint: run the MCP server via the CLI
ENTRYPOINT ["node", "build/cli.js"]
